In [1]:
import numpy as np

In [2]:
arr= np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [7]:
np.random.rand(5)

array([0.96373944, 0.39483499, 0.49001341, 0.11755278, 0.72442046])

In [8]:
np.random.randint(1,10,5)

array([2, 6, 3, 6, 9], dtype=int32)

In [9]:
arr = np.array([[1,2,3],[2,4,5],[8,9,6]])

In [11]:
arr

array([[1, 2, 3],
       [2, 4, 5],
       [8, 9, 6]])

In [12]:
arr.shape

(3, 3)

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr.ndim

2

In [15]:
arr.min()

np.int64(1)

In [16]:
arr.max()

np.int64(9)

In [20]:
arr
arr.sum()

np.int64(40)

In [18]:
arr.argmax()

np.int64(7)

In [23]:
arr

array([[1, 2, 3],
       [2, 4, 5],
       [8, 9, 6]])

In [24]:
np.sum(arr,axis=1)

array([ 6, 11, 23])