In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)

In [3]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [5]:
arr[1:5]

array([12, 13, 14, 15])

In [9]:
arr[-5:]

array([16, 17, 18, 19, 20])

In [11]:
arr = np.arange(1,31).reshape(6,5)


In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [17]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
arr[3:,-3:-1]

array([[18, 19],
       [23, 24],
       [28, 29]])

boolen indexing


In [20]:
arr = np.arange(11,21)

In [21]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool_index = arr%2==0

In [23]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr[bool_index]

array([12, 14, 16, 18, 20])