In [2]:
import numpy as np

In [3]:
a1= np.array([1,2,3,4,5])
a2 = np.array([3,4,5,6,7])

In [5]:
sum_array=(a1+a2)
sum_array


array([ 4,  6,  8, 10, 12])

In [6]:
l = [1,2,3,4,5]
arr = np.array(l)

In [7]:
arr+10

array([11, 12, 13, 14, 15])

In [9]:
arr= np.arange(1,10).reshape(3,3)

In [10]:
arr+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
ar = np.arange(1,21)

In [12]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice= ar[:5]

In [16]:
slice

array([1, 2, 3, 4, 5])

In [17]:
slice=slice*10

In [18]:
slice

array([10, 20, 30, 40, 50])

In [19]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [21]:
mat1

array([[1, 2],
       [3, 4]])

In [22]:
mat2

array([[5, 6],
       [7, 8]])

In [23]:
mat1*mat2

array([[ 5, 12],
       [21, 32]])

In [26]:
mat1 @ mat2 #this is the matrix maltiplication

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [28]:
np.transpose(mat1)

array([[1, 3],
       [2, 4]])

In [29]:
mat1.T

array([[1, 3],
       [2, 4]])

**advance array manipulating**

Stacking array

In [30]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [31]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [35]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]